name = "PseudoGapSolver"
uuid = "7c2a416a-6052-4416-8c70-692550186591"
authors = ["Ka Ho Wong"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"

[compat]
julia = "1.12"
