name = "PseudoGapSolver"
uuid = "7c2a416a-6052-4416-8c70-692550186591"
authors = ["Ka Ho Wong"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.12"
Statistics = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-63c523da284b"

[targets]
test = ["Test"]
